services:

  mysql:
    image: mysql:8.4
    container_name: product-api-mysql
    restart: unless-stopped

    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10

  product-api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: product-api
    restart: unless-stopped

    depends_on:
      mysql:
        condition: service_healthy

    environment:
      DB_HOST: mysql
      DB_NAME: ${DB_NAME}
      DB_USERNAME: root
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}

      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_EXPIRATION: ${JWT_ACCESS_EXPIRATION}
      JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION}

    ports:
      - "8080:8080"

volumes:
  mysql_data: